# Generated by Django 6.0.7 on 2026-07-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_date_alter_groups_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
    ]
