# Generated by Django 6.0.7 on 2026-07-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_date'),
        ('normativ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normativquestion',
            name='normativ',
        ),
        migrations.AddField(
            model_name='normativquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normativ_question', to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='Normativ',
        ),
    ]
